name: C/C++ CI

on:
  pull_request:
  push:
    branches:
      - master
      - devel

jobs:
  build:
    name: Build project

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build project
        run: sudo bash -c ". ./PKGBUILD && ubuntu_pkginstall && notarch_prepare && build && notarch_package"

      - name: Check
        run: filestorage
