name: C/C++ CI

on:
  pull_request:
  push:
    branches: 
    - master
    - devel

jobs:
  build:
    name: Build project

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      
    - name: Initialize
      run: 'cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER=gcc -DCMAKE_CXX_COMPILER=g++ -DPACKAGE_VERSION="github-actions" -DAPPNAME="filestorage" .'
      
    - name: Build
      run: make -j 6
      
    - name: Check
      run: filestorage
